<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Devlead.SourcePack.Integration.Test</RootNamespace>
    <Configurations>Debug;Release;IntegrationTest</Configurations>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <UseDefaultProgram>false</UseDefaultProgram>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'IntegrationTest'">
    <SamplePackageVersion>$(SamplePackageVersion)</SamplePackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Devlead.SourcePack.Sample" VersionOverride="$(SamplePackageVersion)" Condition="'$(Configuration)' == 'IntegrationTest'" />
    <PackageReference Include="Devlead.SourcePack.Sample.Advanced" VersionOverride="$(SamplePackageVersion)" Condition="'$(Configuration)' == 'IntegrationTest'" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
